### ISSUE TITLE
PM comments (commentary run through) - renewables and low carbon

### ISSUE THREAD

**Issue by PM-OCEA** [ischerr/Scottish-Energy-Statistics-Hub#34]
Structure to update to:

- [x] Renewable electricity target
- [x] Electricity generation
  - By fuel
  - Low carbon vs fossil fuels
  - Nuclear vs renewables
- [x] Renewable electricity generation
  - By fuel (just the electricity generated tab - rename to annual, and include a quarterly tab)
  - Proportion of the UK (current Scottish renewables generation)
  - Wind and hydro generation - EU
- [ ] Renewable electricity capacity
  - Operational annual (currently the installed capacity tab in renewable electricity by fuel)
  - Operational quarterly (to be added, broken down by technology)
  - Pipeline
  - LA breakdown (the Renewable electricity by LA tab, but change it from generation to capacity)
- [x] Electricity consumption by fuel
- [x] Renewable sources
  - Wind onshore
  - Wind offshore
  - Hydro
  - Solar PV
  - Tidal
  - Biomass and energy from waste
- [x] Emissions
  - Grid emissions
  - Emissions displaced by renewables

Other points:
- ~~In the electricity consumption tab, add in North and South Scotland~~ 
- [x] Renewable electricity generation/capacity - did we have an estimate for onshore and offshore wind for the earlier years?
- [ ] Renewable heat - size of installation (add in after the tech type tab)
- [x] Remove the emissions tab and retire Scottish GHG, Energy supply emissions and adjusted emissions.  Low carbon economy should be a tab in its own right, with separate tabs for employment and turnover.

**Comment by ischerr** [comment]
Can't compare North Scotland, South Scotland, and rest of GB on current Data, so cannot split out electricity consumption by fuel to include North and South Scotland. The API cannot output England and Wales combined as a proportion of final consumption, and we do not have actual consumption broken down to North and South Scotland.
