### ISSUE TITLE
ESD feedback

### ISSUE THREAD

**Issue by PM-OCEA** [ischerr/Scottish-Energy-Statistics-Hub#42]
- [x] Energy productivity: I ran the new QNAS numbers through the code and the energy prod chart needs updated

- [x] Energy balance: exports and losses % should be 86.9% and final consumption should be 13.1%

- [x] Elec gen by fuel: pull renewables figures from 2004-07 in and update the gif on this basis.  Then, roll back the 2004 and 2005 figures for the 'elec gen low carbon and fossil' tab

- [x] Renewable elec by fuel: Update charts back to 2000

- [x] ~Renewable elec capacity: Were you planning to put the quarterly capacity breakdown by technology into the Hub, or the ESD too?~

- [x] RHI: Update for December 2019

- [x] Biofuels: There might be an update for this out on Fri 31st Jan?

- [x] Comm & locally owned renewables: Fix dates on the subheadings of the charts.  The technology chart isn't updated

- [x] General point - target charts - I notice that a few charts with targets (COLO, energy consumption), the latest year in the subheading refers to the year of the target and not when we have the most recent data

- [x] Domestic EPCs: Stacked bar on the left, change to 2018 only.  Line chart needs an extra point with the RdSAP 9.93 for 2018.  Average EER rating needs charted (but ok to leave this to the hub).  Tenure breakdown chart needs updated

- [x] Wall insulation, loft insulation, boilers: charts all need updated

- [x] Fuel poverty: 2017 data has gone missing in the chart

**Comment by ischerr** [comment]
> Biofuels: There might be an update for this out on Fri 31st Jan? 

Not yet
