### ISSUE TITLE
Stuff to do before ACSES is published

### ISSUE THREAD

**Issue by PM-OCEA** [ischerr/Scottish-Energy-Statistics-Hub#89]
- [x] Renewable capacity by size - the methodology we've used based on REPD is flawed, so pull this data immediately!  Instead use the data that Will sends us for the partially operational sites.  I'll forward you an email with the figures I have.  Not sure what we'll be able to do for a time series on this though

- [x] Electricity system security - replace the large hydro figures with the figure we have for large hydro in Q1 each year from ET 6.1

- [x] Resizing infographics for ACSES format

- [x] Ren elec capacity - add in a number of sites by technology time series in the data tables in the hub - data comes from https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/834143/Regional_statistics__2003-2018__-_number_of_sites.xls

- [x] Sources - incorporate the number of sites data into the sources charts and data table in the hub and in ACSES too

- [x] Smart meter infographic - 1.10 million smart meters were installed in Scotland by June 2020, 39.2% of all Scottish meters.
 
- [x] Update energy productivity if it changes with the new data this week (ACSES and infographics)

- [x] Update system security with 2019/20 with the new power stations stuff from DUKES (ACSES and infographics)

- [x] Update the Covid-19 page

**Comment by ischerr** [comment]
- [ ] Renewable capacity by size time series
